import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LaCroix Styles",
  description: "Generated by create next app",
  icons: "/favicon.png",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <header> <Navbar /> </header>
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-screen antialiased bg-linear-to-b from-[#ff8ec9]  via-white via-70% to-[#fed3e7] from-10%`}
      >
        {children}
      </body>
    </html>
  );
}
