import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer"
import { ReduxProvider } from "./ReduxProvider";
import { Roboto } from 'next/font/google';

const RobotoFont = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LaCroix Styles",
  description: "Generated by create next app",
  icons: {
   
    icon: [
      { url: "/favicon.png", sizes: "32x32" }, 
    ],
    
    shortcut: "/Logo_LAcroix Styles_192_Android.png", 
   
    apple: "/Logo_LAcroix Styles_192x192.png",
  },
  
  manifest: "/manifest.json",

  appleWebApp: {
    
    capable: true, 
    title: 'LaCroix Styles',
    statusBarStyle: 'black-translucent',
  }
  
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
      <body
        className={`${RobotoFont.className} min-h-screen overflow-x-hidden antialiased bg-gradient-to-b from-[#ff8ec9]  via-white via-70% to-[#fed3e7]`}
      >
        
          <Navbar />

          {children}

          <Footer />
        
      </body>
      </ReduxProvider>
    </html>
  );
}
